- alias: Wand Gesture - Down
  description: Slowly dim lights to off
  trigger:
    platform: event
    event_type: wand_gesture
    event_data:
      gesture: down
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
    data:
      brightness: 0
      transition: 5
  id: e30a360dac57451aae2920e6cecc07b5
- alias: Wand Gesture - Up
  description: Slowly dim lights to max brightness
  trigger:
    platform: event
    event_type: wand_gesture
    event_data:
      gesture: up
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
    data:
      brightness: 255
      transition: 5
  id: 08cdc3a5b92b4712bcd13efd75d0c652
- alias: Wand Gesture - Left
  description: Change to purple with wave effect
  trigger:
    platform: event
    event_type: wand_gesture
    event_data:
      gesture: left
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
    data:
      brightness: 180
      rgb_color:
      - 128
      - 0
      - 128
      transition: 2
  - delay: 00:00:02
  - service: light.turn_on
    target:
      entity_id: light.hue_color_lamp_2
    data:
      brightness: 210
      transition: 1
  id: 9d997ef913ce40f9b62ba3f8d7eaf015
- alias: Wand Gesture - Right
  description: Change to red
  trigger:
    platform: event
    event_type: wand_gesture
    event_data:
      gesture: right
  action:
  - service: light.turn_on
    target:
      entity_id:
      - light.hue_color_lamp_1
      - light.hue_color_lamp_2
    data:
      brightness: 200
      rgb_color:
      - 255
      - 0
      - 0
      transition: 2
  id: aa7662f98aa9474a87b3d9911c4933a4
- alias: "Wand Gesture - Still"
  description: "Random color fade effect"
  trigger:
    platform: event
    event_type: wand_gesture
    event_data:
      gesture: "still"
  action:
    - service: light.turn_on
      target:
        entity_id:
          - light.hue_color_lamp_1
          - light.hue_color_lamp_2
      data:
        brightness: 150
        rgb_color: [255, 0, 0]
        transition: 1
    
    - variables:
        available_colors:
          - [255, 0, 0]
          - [0, 255, 0]
          - [0, 0, 255]
          - [255, 255, 0]
          - [255, 0, 255]
          - [0, 255, 255]
          - [255, 165, 0]
    
    - repeat:
        count: 20
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - light.hue_color_lamp_1
                - light.hue_color_lamp_2
            data:
              rgb_color: "{{ available_colors | random }}"
              brightness: 150
              transition: 3
          - delay: "00:00:03"
  mode: restart
  id: 1acdd4dd5ff14bb8bf079fe519271885