version: '3.8'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    volumes:
      - ./:/config
    environment:
      - TZ=America/New_York
    ports:
      - 8123:8123
    network_mode: host